In [1]:
import numpy as np

1. Crea un array 1D con 50 valores aleatorio del 10 al 99. Accede a los elementos en las posiciones múltiplos de 5.

In [4]:
array1 = np.random.randint(10, 100, size=50)

In [5]:
array1

array([40, 68, 97, 48, 18, 46, 25, 72, 17, 20, 68, 57, 62, 11, 74, 80, 81,
       22, 27, 31, 64, 45, 83, 78, 98, 22, 20, 54, 47, 65, 30, 18, 89, 16,
       61, 78, 93, 38, 15, 13, 74, 24, 60, 54, 53, 61, 83, 27, 85, 38])

In [7]:
array1[::5]

array([40, 46, 68, 80, 64, 22, 30, 78, 74, 61])

2. Crea un array 1D con 30 valores del 1 al 20 (ambos incluidos). Utiliza indexación para obtener los elementos en las posiciones impares.

In [8]:
array2 = np.random.randint(1, 21, size=30)

In [9]:
array2

array([15, 12, 14, 15, 11, 13, 10,  4, 18,  8, 13,  6, 18,  7,  1,  5, 18,
       18,  1, 13, 18,  9, 13,  4, 20, 16, 16,  8, 10, 11])

In [10]:
array2[1::2]

array([12, 15, 13,  4,  8,  6,  7,  5, 18, 13,  9,  4, 16,  8, 11])

3. Crea un array 2D de forma (4, 6) con números aleatorios decimales (no deben estar comprendidos solo entre 0 y 1). Accede a la última fila de la matriz. Los decimales deben estar redondeados a 2 decimales.

In [62]:
array3 = np.random.rand(4, 6)*100

In [63]:
array3

array([[39.40830581, 18.04714584, 83.41595149, 54.70865004, 72.52637269,
        61.07599392],
       [99.65343205, 25.50679137, 96.94501736, 33.07220403, 64.14250572,
        37.9107263 ],
       [86.87593549, 14.64905689, 79.24416473, 44.70243062, 65.59071718,
        70.93925014],
       [89.13196769, 54.15945371, 94.75799533, 93.07857388, 19.486771  ,
        49.39628605]])

In [64]:
np.round(array3, 2)[-1]

array([89.13, 54.16, 94.76, 93.08, 19.49, 49.4 ])

4. BONUS: Crea un array 3D de forma (2, 3, 5) y 30 elementos con números enteros entre 0 y 100 (ambos incluidos). Reemplaza los elementos en posiciones múltiplos de 3 por 0.

In [60]:
array4 = np.random.randint(0, 101, (2, 3, 5))

In [61]:
array4

array([[[13,  0, 90, 48, 69],
        [98, 20, 95, 57, 46],
        [49, 24, 43, 62, 92]],

       [[37, 11, 82, 61, 64],
        [15, 85, 37, 69, 74],
        [43, 44, 34, 33, 51]]])

In [ ]:
array4.flatten

In [55]:
array4

array([[[  0,  49,  84,   0,  27],
        [  0,  30,  95,   0,  30],
        [  0,  10,  81,   0,  31]],

       [[  0, 100,  67,   0,  44],
        [  0,  73,   8,   0,  74],
        [  0,  44,  50,   0,  44]]])

1. Crea un array 3D de forma (2, 3, 4) con valores aleatorios entre 1 y 100 (ambos inclusive). Utiliza reshape para convertirlo en un array 2D. Deberás pensar en la forma que es correcta para hacer este cambio.

In [65]:
array5 = np.random.randint(1, 101, (2, 3, 4))

In [66]:
array5

array([[[85, 32, 41, 56],
        [43, 90, 90, 77],
        [45, 72, 71, 77]],

       [[18, 94, 46, 83],
        [79, 35, 47, 23],
        [19, 53, 87, 78]]])

In [67]:
array5_re = np.reshape(array5, (6, 4))

In [68]:
array5_re

array([[85, 32, 41, 56],
       [43, 90, 90, 77],
       [45, 72, 71, 77],
       [18, 94, 46, 83],
       [79, 35, 47, 23],
       [19, 53, 87, 78]])

2. Crea un array 3D de forma (3, 4, 5) con valores enteros del 1 al 61 (sin incluir). Utiliza reshape para convertirlo en un array 2D.

In [69]:
array6 = np.random.randint(1, 61, (3, 4, 5))

In [70]:
array6

array([[[45, 45, 33, 22, 14],
        [23, 45, 35, 56, 60],
        [47, 39, 29, 13, 40],
        [58, 26, 25,  3,  9]],

       [[32, 50,  3, 59, 10],
        [33,  1, 31, 55, 15],
        [12, 55, 24, 22, 44],
        [25, 12, 25, 26,  8]],

       [[18, 31, 57,  9, 11],
        [50, 45, 17, 13,  6],
        [ 8, 38, 58,  7, 14],
        [54,  1,  3, 27, 53]]])

In [71]:
array6_re = np.reshape(array6, (12, 5))

In [72]:
array6_re

array([[45, 45, 33, 22, 14],
       [23, 45, 35, 56, 60],
       [47, 39, 29, 13, 40],
       [58, 26, 25,  3,  9],
       [32, 50,  3, 59, 10],
       [33,  1, 31, 55, 15],
       [12, 55, 24, 22, 44],
       [25, 12, 25, 26,  8],
       [18, 31, 57,  9, 11],
       [50, 45, 17, 13,  6],
       [ 8, 38, 58,  7, 14],
       [54,  1,  3, 27, 53]])

3. Utiliza el array 3D del ejercicio 2 de reshape. Utiliza transpose para permutar los ejes y obtener un nuevo array con forma (5, 4, 3).

In [74]:
array6

array([[[45, 45, 33, 22, 14],
        [23, 45, 35, 56, 60],
        [47, 39, 29, 13, 40],
        [58, 26, 25,  3,  9]],

       [[32, 50,  3, 59, 10],
        [33,  1, 31, 55, 15],
        [12, 55, 24, 22, 44],
        [25, 12, 25, 26,  8]],

       [[18, 31, 57,  9, 11],
        [50, 45, 17, 13,  6],
        [ 8, 38, 58,  7, 14],
        [54,  1,  3, 27, 53]]])

In [76]:
array6_trans = np.transpose(array6)

In [77]:
array6_trans

array([[[45, 32, 18],
        [23, 33, 50],
        [47, 12,  8],
        [58, 25, 54]],

       [[45, 50, 31],
        [45,  1, 45],
        [39, 55, 38],
        [26, 12,  1]],

       [[33,  3, 57],
        [35, 31, 17],
        [29, 24, 58],
        [25, 25,  3]],

       [[22, 59,  9],
        [56, 55, 13],
        [13, 22,  7],
        [ 3, 26, 27]],

       [[14, 10, 11],
        [60, 15,  6],
        [40, 44, 14],
        [ 9,  8, 53]]])

4. Utiliza el array 3D del ejercicio 2 de reshape. Utiliza transpose para cambiar el orden de los ejes y obtener un nuevo array con forma (3, 5, 4).

In [78]:
array6_trans2 = np.transpose(array6, (3, 5, 4))

AxisError: axis 3 is out of bounds for array of dimension 3